# Generated by Django 6.0.5 on 2026-06-01 22:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('won', 'Won'), ('lost', 'Lost')], default='active', max_length=6)),
                ('difficulty', models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'expert')])),
                ('rows', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('is_revealed', models.BooleanField(default=False)),
                ('is_crossed', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_mine', models.BooleanField(default=False)),
                ('adjacent_mines', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'unique_together': {('game', 'row', 'column')},
            },
        ),
    ]
